-- DROP DATABASE IF EXISTS $MYSQL_ENV_MYSQL_DATABASE;

CREATE USER '$MYSQL_ENV_MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_ENV_MYSQL_PASSWORD';

CREATE DATABASE $MYSQL_ENV_MYSQL_DATABASE;

GRANT ALL ON $MYSQL_ENV_MYSQL_DATABASE.* TO '$MYSQL_ENV_MYSQL_USER'@'localhost';

FLUSH PRIVILEGES;
