DROP DATABASE IF EXISTS $MYSQL_ENV_MYSQL_DATABASE;
CREATE DATABASE $MYSQL_ENV_MYSQL_DATABASE;

FLUSH PRIVILEGES;

SET @ORIGINAL_SQL_MODE=@@SQL_MODE, SQL_MODE='ANSI';
USE $MYSQL_ENV_MYSQL_DATABASE;
DROP PROCEDURE IF EXISTS $MYSQL_ENV_MYSQL_DATABASE.drop_user_$MYSQL_ENV_MYSQL_USER_if_exists;
DELIMITER $$
CREATE PROCEDURE $MYSQL_ENV_MYSQL_DATABASE.drop_user_$MYSQL_ENV_MYSQL_USER_if_exists()
BEGIN
  DECLARE users INT DEFAULT 0;
  SELECT COUNT(*) INTO @users FROM mysql.user WHERE User = '$MYSQL_ENV_MYSQL_USER' AND Host='localhost';
  IF @users > 0 THEN
      SET @sqlstring = CONCAT("DROP USER ", "$MYSQL_ENV_MYSQL_USER", "@\'localhost\'" );
      PREPARE statement FROM @sqlstring ;
      EXECUTE statement;
      SELECT CONCAT("DROPPED PRE-EXISTING USER: ", $MYSQL_ENV_MYSQL_USER, "@localhost" ) as info;
  END IF;
END ;$$
DELIMITER;
CALL $MYSQL_ENV_MYSQL_DATABASE.drop_user_$MYSQL_ENV_MYSQL_USER_if_exists();
DROP PROCEDURE IF EXISTS $MYSQL_ENV_MYSQL_DATABASE.drop_user_$MYSQL_ENV_MYSQL_USER_if_exists;
SET SQL_MODE=@ORIGINAL_SQL_MODE;

FLUSH PRIVILEGES;

CREATE USER '$MYSQL_ENV_MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_ENV_MYSQL_PASSWORD';

GRANT ALL ON $MYSQL_ENV_MYSQL_DATABASE.* TO '$MYSQL_ENV_MYSQL_USER'@'localhost';

FLUSH PRIVILEGES;
